### ISSUE TITLE
Pick a license...

### ISSUE THREAD

**Issue by Raven24** [Raven24/diaspora-federation#7]
IMHO there are three possible choices for this gem

* [MIT](https://en.wikipedia.org/wiki/MIT_License)
* [BSD](https://en.wikipedia.org/wiki/BSD_licenses)
* [ISC](https://en.wikipedia.org/wiki/ISC_license)

anyone got some specific pros/cons?

**Comment by dimaursu** [comment]
There are more than one licenses that were invented at MIT, but it's safe to assume in this case we are talking about Expat (the one used in the Ruby community). I'd go with Apache here, for the patent reason: https://www.gnu.org/licenses/license-list.html#Expat ; These guys did their homework, I'm sure they know what they are talking about.

On a side note, this is a very special case of a piece of software: it's an implementation of what wants to be a protocol: maybe the protocol conventions should be enforced by the license? If that is so, to what degree? How can we ensure that the protocol is open to extension and improvements, yet nobody would break it? 

Is there any analogical & popular pieces of software? (popular - because it's more likely they hit legal issues)

**Comment by Raven24** [comment]
this is closed by 6c1e96b15aae55a2db130cf56089f565748ce6f3 ... thanks for the opinions @ all
